### ISSUE TITLE
pyros-setup osrf buildfarm failed build

### ISSUE THREAD

**Issue by asmodehn** [pyros-dev/pyros-setup#21]
```
See <http://build.ros.org/job/Ibin_uT64__pyros_setup__ubuntu_trusty_amd64__binary/9/>

------------------------------------------
[...truncated 2191 lines...]
ros-indigo-rosunit set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
 ---> eabf3eda8673
Removing intermediate container 41aba72c94d2
Step 36 : USER buildfarm
 ---> Running in dbe4c8d25459
 ---> 75d2276c0f88
Removing intermediate container dbe4c8d25459
Step 37 : ENTRYPOINT sh -c
 ---> Running in c3ce3087c2d7
 ---> 5b46d7b6f1a0
Removing intermediate container c3ce3087c2d7
Step 38 : CMD PYTHONPATH=/tmp/ros_buildfarm:$PYTHONPATH PATH=/usr/lib/ccache:$PATH python3 -u /tmp/ros_buildfarm/scripts/release/build_binarydeb.py indigo pyros_setup --sourcedeb-dir /tmp/binarydeb
 ---> Running in 6d66caf697d0
 ---> 655c01d8ba42
Removing intermediate container 6d66caf697d0
Successfully built 655c01d8ba42
+ echo # END SECTION
# END SECTION
+ echo # BEGIN SECTION: Run Dockerfile - build binarydeb
# BEGIN SECTION: Run Dockerfile - build binarydeb
+ docker run --rm --cidfile=<http://build.ros.org/job/Ibin_uT64__pyros_setup__ubuntu_trusty_amd64__binary/ws/docker_build_binarydeb/docker.cid> -e=HOME= --net=host -v <http://build.ros.org/job/Ibin_uT64__pyros_setup__ubuntu_trusty_amd64__binary/ws/ros_buildfarm>:/tmp/ros_buildfarm:ro -v <http://build.ros.org/job/Ibin_uT64__pyros_setup__ubuntu_trusty_amd64__binary/ws/binarydeb>:/tmp/binarydeb -v /home/jenkins-slave/.ccache:/home/buildfarm/.ccache binarydeb_build.indigo_ubuntu_trusty_amd64_pyros_setup
# BEGIN SUBSECTION: build binarydeb
Package 'ros-indigo-pyros-setup' version: 0.1.0-0trusty-20160510-050234-0700
Invoking 'apt-src build ros-indigo-pyros-setup' in '/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0'
I: Building in /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0 ..
dpkg-buildpackage: source package ros-indigo-pyros-setup
dpkg-buildpackage: source version 0.1.0-0trusty-20160510-050234-0700
dpkg-buildpackage: source distribution trusty
dpkg-buildpackage: source changed by AlexV <asmodehn@gmail.com>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build ros-indigo-pyros-setup-0.1.0
 fakeroot debian/rules clean
dh  clean
   dh_testdir
Unknown option: buildsystem
dh_testdir: warning: ignored unknown options in DH_OPTIONS
   dh_auto_clean
   dh_clean
Unknown option: buildsystem
dh_clean: warning: ignored unknown options in DH_OPTIONS
        rm -f debian/ros-indigo-pyros-setup.substvars
        rm -f debian/ros-indigo-pyros-setup.*.debhelper
        rm -rf debian/ros-indigo-pyros-setup/
        rm -f debian/*.debhelper.log
        rm -f debian/files
        find .  \( \( -type f -a \
                \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
                 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
                 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
                 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
                \) -exec rm -f {} + \) -o \
                \( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
        rm -f *-stamp
 debian/rules build
dh  build
   dh_testdir
Unknown option: buildsystem
dh_testdir: warning: ignored unknown options in DH_OPTIONS
   debian/rules override_dh_auto_configure
make[1]: Entering directory `/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0'
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi && \
        dh_auto_configure -- \
                -DCATKIN_BUILD_BINARY_PACKAGE="1" \
                -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
                -DCMAKE_PREFIX_PATH="/opt/ros/indigo"
        mkdir -p obj-x86_64-linux-gnu
        cd obj-x86_64-linux-gnu
        cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo -DCMAKE_PREFIX_PATH=/opt/ros/indigo
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/x86_64-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/x86_64-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Using CATKIN_DEVEL_PREFIX: /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Found PythonInterp: /usr/bin/python (found version "2.7.6")
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Skip enable_testing() when building binary package
-- Using CATKIN_TEST_RESULTS_DIR: /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/test_results
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.18
-- Loading catkin-pip.cmake from /opt/ros/indigo/share/catkin_pure_python/cmake...
-- Loading /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/.catkin-pip-setup-devel.cmake...
-- Catkin pip PYTHONPATH : /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel/lib/python2.7/site-packages:/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel/lib/python2.7/dist-packages:/opt/ros/indigo/lib/python2.7/dist-packages:/tmp/ros_buildfarm:
-- Catkin pip PATH : /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel/bin:/opt/ros/indigo/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
--     ... Catkin pip was not found in /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel/bin ...
--     ... Retrieving catkin_pure_python requirements using system pip ...
--     ... Done ... [0]:
--     ... Running python -m pip install -r /opt/ros/indigo/share/catkin_pure_python/cmake/catkin-pip-fixups.req --ignore-installed --src /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0 --exists-action b --prefix /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel ...
--     ... Done ... [0]: Collecting pip (from -r /opt/ros/indigo/share/catkin_pure_python/cmake/catkin-pip-base.req (line 3))
  Downloading pip-8.1.1-py2.py3-none-any.whl (1.2MB)
Collecting setuptools (from -r /opt/ros/indigo/share/catkin_pure_python/cmake/catkin-pip-base.req (line 4))
  Downloading setuptools-21.0.0-py2.py3-none-any.whl (509kB)
Collecting nose (from -r /opt/ros/indigo/share/catkin_pure_python/cmake/catkin-pip-fixups.req (line 7))
  Downloading nose-1.3.7-py2-none-any.whl (154kB)
Installing collected packages: pip, setuptools, nose
Successfully installed nose-1.3.7 pip-8.1.1 setuptools-21.0.0

-- Found catkin_pure_python pip command at /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel/bin/pip.
-- Found catkin_pure_python nosetests command at /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel/bin/nosetests.
--     ... Running /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel/bin/pip install -r /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/requirements.txt --ignore-installed --src /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0 --exists-action b --prefix /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel ...
--     ... Done ... [0]: Collecting nose>=1.3.7 (from -r /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/requirements.txt (line 4))
  Using cached nose-1.3.7-py2-none-any.whl
Installing collected packages: nose
Successfully installed nose-1.3.7

--     ... Running /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel/bin/pip install -e . --prefix /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel ...
--     ... Done ... [0]: Obtaining file:///tmp/binarydeb/ros-indigo-pyros-setup-0.1.0
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from pyros-setup==0.1.0)
Collecting importlib (from pyros-setup==0.1.0)
  Downloading importlib-1.0.3.tar.gz
Building wheels for collected packages: importlib
  Running setup.py bdist_wheel for importlib: started
  Running setup.py bdist_wheel for importlib: finished with status 'done'
  Stored in directory: /home/buildfarm/.cache/pip/wheels/2a/04/fb/873fc6754f3d84f4ad1ee05bd2e63bc52dc883fbe314c5801a
Successfully built importlib
Installing collected packages: importlib, pyros-setup
  Running setup.py develop for pyros-setup
Successfully installed importlib-1.0.3 pyros-setup-0.1.0

-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu
        cd /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0
make[1]: Leaving directory `/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0'
   debian/rules override_dh_auto_build
make[1]: Entering directory `/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0'
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi && \
        dh_auto_build
        cd obj-x86_64-linux-gnu
        make -j1
make[2]: Entering directory `/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu'
/usr/bin/cmake -H/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0 -B/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/CMakeFiles /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[3]: Entering directory `/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu'
/usr/bin/cmake -E cmake_progress_start /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/CMakeFiles 0
make[2]: Leaving directory `/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu'
        cd /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0
make[1]: Leaving directory `/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0'
   debian/rules override_dh_auto_test
make[1]: Entering directory `/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0'
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
echo -- Running tests. Even if one of them fails the build is not canceled.
-- Running tests. Even if one of them fails the build is not canceled.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi && \
        dh_auto_test || true
make[1]: Leaving directory `/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0'
 fakeroot debian/rules binary
dh  binary
   dh_testroot
   dh_prep
        rm -f debian/ros-indigo-pyros-setup.substvars
        rm -f debian/ros-indigo-pyros-setup.*.debhelper
        rm -rf debian/ros-indigo-pyros-setup/
   dh_installdirs
Unknown option: buildsystem
dh_prep: warning: ignored unknown options in DH_OPTIONS
Unknown option: buildsystem
dh_installdirs: warning: ignored unknown options in DH_OPTIONS
        install -d debian/ros-indigo-pyros-setup
   debian/rules override_dh_auto_install
make[1]: Entering directory `/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0'
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi && \
        dh_auto_install
        cd obj-x86_64-linux-gnu
        make -j1 install DESTDIR=/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/debian/ros-indigo-pyros-setup AM_UPDATE_INFO_DIR=no
make[2]: Entering directory `/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu'
/usr/bin/cmake -H/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0 -B/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/CMakeFiles /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[3]: Entering directory `/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu'
/usr/bin/cmake -E cmake_progress_start /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/CMakeFiles 0
make -f CMakeFiles/Makefile2 preinstall
make[3]: Entering directory `/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu'
make[3]: Nothing to be done for `preinstall'.
make[3]: Leaving directory `/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu'
Install the project...
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: "None"
-- Loading /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/.catkin-pip-setup-install.cmake...
make[2]: Leaving directory `/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu'
make[1]: Leaving directory `/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0'
# END SUBSECTION
CMake Error at .catkin-pip-setup-install.cmake:48 (file):
  file Internal CMake error when trying to open file:
  /opt/ros/indigo/_setup_util.py for writing.
Call Stack (most recent call first):
  cmake_install.cmake:38 (include)


make[2]: *** [install] Error 1
dh_auto_install: make -j1 install DESTDIR=/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/debian/ros-indigo-pyros-setup AM_UPDATE_INFO_DIR=no returned exit code 2
make[1]: *** [override_dh_auto_install] Error 2
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
E: Building failed
Traceback (most recent call last):
  File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 120, in build_binarydeb
    subprocess.check_call(cmd, cwd=source_dir)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-src', 'build', 'ros-indigo-pyros-setup']' returned non-zero exit status 1

--------------------------------------------------------------------------------------------------
`apt-src build ros-indigo-pyros-setup` failed.
This is usually because of an error building the package.
The traceback from this failure (just above) is printed for completeness, but you can ignore it.
You should look above `E: Building failed` in the build log for the actual cause of the failure.
--------------------------------------------------------------------------------------------------

Build step 'Execute shell' marked build as failure
[ssh-agent] Stopped.
[description-setter] Could not determine description.
```

**Comment by asmodehn** [comment]
Need to find a way to fix this, or build a deb package in another way (see https://github.com/asmodehn/pyros-setup/issues/20)

**Comment by asmodehn** [comment]
This was a catkin_pure_python issue. It has now been fixed.
Anyway we should NOT generate a ROS package from pyros-setup to avoid confusion.
pyros-setup should be used only from pip or standard python env, if needed to bridge with ROS environment.
