### ISSUE TITLE
Error running self tests on Trusty

### ISSUE THREAD

**Issue by asmodehn** [pyros-dev/pyros-setup#7]
```
alexv@asmodehn:~$ pyros_setup 
Traceback (most recent call last):
  File "/usr/local/bin/pyros_setup", line 9, in <module>
    load_entry_point('pyros-setup==0.0.11', 'console_scripts', 'pyros_setup')()
  File "/usr/local/lib/python2.7/dist-packages/pyros_setup/__main__.py", line 21, in nosemain
    nose.run(argv=args)
  File "/usr/lib/python2.7/dist-packages/nose/core.py", line 301, in run
    return TestProgram(*arg, **kw).success
  File "/usr/lib/python2.7/dist-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/lib/python2.7/dist-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/usr/lib/python2.7/dist-packages/nose/core.py", line 62, in run
    test(result)
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 176, in __call__
    return self.run(*arg, **kw)
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 223, in run
    test(orig)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 71, in run
    for test in self._tests:
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 98, in _get_tests
    for test in self.test_generator:
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 191, in loadTestsFromDir
    entry_path, discovered=True)
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 426, in loadTestsFromName
    discovered=discovered)
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 347, in loadTestsFromModule
    tests.extend(self.loadTestsFromDir(module_path))
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 191, in loadTestsFromDir
    entry_path, discovered=True)
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 426, in loadTestsFromName
    discovered=discovered)
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 328, in loadTestsFromModule
    elif isfunction(test) and self.selector.wantFunction(test):
  File "/usr/lib/python2.7/dist-packages/nose/selector.py", line 144, in wantFunction
    funcname = function.__name__
  File "/usr/local/lib/python2.7/dist-packages/bzrlib/lazy_import.py", line 106, in __getattribute__
    obj = _replace()
  File "/usr/local/lib/python2.7/dist-packages/bzrlib/lazy_import.py", line 88, in _replace
    extra=e)
bzrlib.errors.IllegalUseOfScopeReplacer: ScopeReplacer object 'do_catching_redirections' was used incorrectly: Object already cleaned up, did you assign it to another variable?: _factory
```

**Comment by asmodehn** [comment]
```
alexv@asmodehn:~$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nose
>>> nose.__version__
'1.3.1'
>>> import bzrlib
>>> bzrlib.__version__
'2.1.4'
>>> 
```

**Comment by asmodehn** [comment]
Note the pacakge v0.0.11 seems to work fine except for this self test.

**Comment by asmodehn** [comment]
Looks like a problem in the test discovery from nose.
1.3.7 works fine. We should enforce this one.

**Comment by asmodehn** [comment]
Fix implemented in master.
Needs testing.

**Comment by asmodehn** [comment]
seems fine now. closing.
